# Generated by Django 5.2.13 on 2026-04-21 09:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0009_alter_applicationconfiguration_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_prompt_template",
            field=models.TextField(
                blank=True,
                help_text="Custom prompt template for AI classification. Available placeholders: {filename}, {content}, {available_tags}, {available_correspondents}",
                null=True,
                verbose_name="Custom AI prompt template",
            ),
        ),
    ]
